apiVersion: v1
kind: Service
metadata:
  name: sketch-service
spec:
  selector:
    app: hello-python
  ports:
  - protocol: "TCP"
    port: 7000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sketch-python
spec:
  selector:
    matchLabels:
      app: sketch-python
  replicas: 4
  template:
    metadata:
      labels:
        app: sketch-python
    spec:
      containers:
      - name: sketch-python
        image: kumarnitesh2000/sketch_backend:yahh
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

