name: DockerCI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Build DockerImage
      run: |
        docker build -t kumarnitesh2000/sketch_backned:1.0 .
        
        
