name: DockerCI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: DockerLogin
      env:
        USER: ${{ secrets.DOCKERHUB_USER }}
        PASSD: ${{ secrets.DOCKERHUB_PASSWD }}
      run: |
        winpty docker login -u $USER -p $PASSWD 
    - name: PrintCommit
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        git_branch=${GITHUB_REF##*/}
        echo $git_branch
        echo $git_hash   
    - name: Build DockerImage
      run: |
        docker build -t sketch .
    - name: Push DockerImage
      env: 
        hash: $(git rev-parse --short "$GITHUB_SHA") 
      run: |
        docker tag sketch kumarnitesh2000/sketch_backend:$hash
        docker push kumarnitesh2000/sketch_backend:$hash  
        
