name: DockerCI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: PrintCommit
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        git_branch=${GITHUB_REF##*/}
        echo $git_branch
        echo $git_hash   
    - name: Build DockerImage
      run: |
        docker build -t kumarnitesh2000/sketch_backned:1.0 .
        
        
